### ISSUE TITLE
Build 

### ISSUE THREAD

**Issue by FinlayShaw02** [umaaaaaaaaa/Christmas_Game#1]
Hi, having some issues opening and building the project, do you have a build configuration you could give me to use so i can run your project.
Thanks,
Fin

**Comment by umaaaaaaaaa** [comment]
Hi, try to put all the files from the core, qui and imgs folders in one folder together with GAME4.pro file. After that, open Qt, and find the open project button, then open GAME4.pro file from your folder. After that, by default, in the build configuration creation will be specified one debug and one release for each Qt profile, click the project settings button and then the build will begin. I repeated all these actions, it should work. 
I hope this will help solve the problem.
